### ISSUE TITLE
pip2 install lyipc

### ISSUE THREAD

**Issue by joamatab** [atait/klayout-ipc#5]
pip install lyipc works great

how can we pip2 install lyipc for python2?

**Comment by joamatab** [comment]
git clone git@github.com:atait/klayout-gadgets.git
pip install klayout-gadgets/klayout_dot_config/python

the backwards compatibility fails for klayout-gadgets.

![image](https://user-images.githubusercontent.com/4514346/46976495-7f008f80-d07e-11e8-9478-35c7667f9097.png)

**Comment by atait** [comment]
Ah yes that doesn’t seem too hard, as long as that is the only incompatibility. I will try to make lygadgets universal, but it is not a priority for lyipc and lytest. In general, would it be possible for you to use python 3? Python 2 will officially stop being supported later this year.
